# Generated by Django 3.1.6 on 2021-02-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_post_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
